# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf63b7dc55a608356f013e58b75824c4fc069b055d415c259680486a2a064f5126b63a28d3f89e283c7b26396c30ce6609bd20e54b19ab9e6faf3741b24f125b

test:
  secret_key_base: 7a74d7898466886f9f64795a67c4c451db5ea93708f3acabb56836dd13f160fba594c70cb66302103c9dacd516c741bcd216cf56672a8d76f9ff3dcc347d639e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
